### ISSUE TITLE
Populated text for attacks cause action failure

### ISSUE THREAD

**Issue by baileymh** [hktrpg/foundryVTT-default-name#1]
Hi!

Encountered a problematic bug. With your mod enabled, when someone goes to make an attack, the "e.g. 2d20kl" is being created in the text box, and without deleting it, results in an error on attack/use that prevents the action from working.

![image](https://user-images.githubusercontent.com/48079051/109896393-e07d2500-7c5e-11eb-831a-b1c5c1e2cf41.png)

**Comment by zeteticl** [comment]
Thank for report. 
I think it would fixed in the v1.1.0
Please check.

**Comment by zeteticl** [comment]
@baileymh  which system is it?

**Comment by baileymh** [comment]
It was for PF1.
